### ISSUE TITLE
Update the package name "candy-create-app" to "create-candy-app"

### ISSUE THREAD

**Issue by cchaonie** [xun082/create-neat#1]
If the package name is `create-XXX`, then it can be used like "npm create xxx", for example, `npm create vite`. From the user's perspective, it would be easier to use it(no need to install it locally).

Here is the vite source for cli: https://github.com/vitejs/vite/blob/main/packages/create-vite/package.json

**Comment by xun082** [comment]
thanks，the package name will be changed in the next update,，but I can't think of a better name, so I haven't changed it

**Comment by xun082** [comment]
thanks，I will change it in the next update, but I haven't come up with a good name yet.

**Comment by cchaonie** [comment]
"create-candy-app" sounds cool to me 😄

**Comment by xun082** [comment]
modified
