### ISSUE TITLE
添加安装dependencies能力

### ISSUE THREAD

**Issue by qq1051766345** [xun082/create-neat#104]
### Is your feature request related to a problem? Please describe it

目前安装依赖模块只能安装devDependencies,有些插件会引入dependencies依赖所以需要增加这个能力****

### Describe the solution you'd like

在添加逻辑增加安装dependencies

### What is the motivation / use case for changing the behavior?

重构

**Comment by FlyAboveGrass** [comment]
this issue should be closed.
