### ISSUE TITLE
任务待办列表

### ISSUE THREAD

**Issue by xun082** [xun082/create-neat#2]
1.  逐步优化用户体验效果,编写更完美的使用文档；
2.  添加对 vue 的支持；
3.  命令行快速创建文件,例如 pages 页面；
4.  优化 webpack 配置；
5.  配置更完善的 eslint 和 prettierrc；
6.  完善组件个数统计功能的正则匹配或者直接切换成babel;
7.  最后你有什么好点的想法,只要是符合脚手架主题的都可以做......

**Comment by penghei** [comment]
大佬！tql！
我有个仅个人的想法，脚手架是不是可以更偏向哪个方面，比如umi有自己的路由，各种中台的pro整合了很多现成页面，create-next-app有ssr，类似这种。我觉得如果只是创建一个web项目，vite的社区就有很多模板，可以用那些，那这个项目的特点就不算很突出了。

**Comment by xun082** [comment]
> 大佬！tql！ 我有个仅个人的想法，脚手架是不是可以更偏向哪个方面，比如umi有自己的路由，各种中台的pro整合了很多现成页面，create-next-app有ssr，类似这种。我觉得如果只是创建一个web项目，vite的社区就有很多模板，可以用那些，那这个项目的特点就不算很突出了。

后续会做，但不是现在，个人开发都忙不过来了，大把东西要学的......
