### ISSUE TITLE
bug: 进入终端以后ctrl+C取消失败而是一直进行下去

### ISSUE THREAD

**Issue by CodeGetters** [xun082/create-neat#229]
### Current behavior

![image](https://github.com/xun082/create-neat/assets/109447998/595e7dfc-0bbe-4a76-a550-1b350fad1f69)

### Minimum reproduction code

none

### Steps to reproduce

npm i -g create-neat

npx create-neat xxx

ctrl+c 取消执行

### Expected behavior

ctrl + C应该马上退出执行

### Package version

1.0.6

### Template Package

react-web-ts

### Node.js version

20.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by uaenaTzx** [comment]
看图片这个是老版本的包，这个问题在新版已经得到解决啦，可以等待新版发布🫰

**Comment by CodeGetters** [comment]
> 看图片这个是老版本的包，这个问题在新版已经得到解决啦，可以等待新版发布🫰

确实是哈哈哈，看见代码中有相关的内容了
