### ISSUE TITLE
基于Vite的配置选择

### ISSUE THREAD

**Issue by zhuba-Ahhh** [xun082/create-neat#37]
### Is your feature request related to a problem? Please describe it

长期的话有考虑Vite或者其他打包工具的可能嘛，（虽然说基于目前该项目的情况看成本确实很高）

### Describe the solution you'd like

Vite的性能和流行性确实很不错，建议后期有机会可以实现相关能力

### Teachability, documentation, adoption, migration strategy

用户能选配Vite

### What is the motivation / use case for changing the behavior?

Vite的快

**Comment by xun082** [comment]
在计划当中的，目前正在重构，通过插件的方式，提供用户不同的选择，不同的构建工具生成不同的基础模板
