### ISSUE TITLE
命令行交互使用的库有哪些？

### ISSUE THREAD

**Issue by WakerCN** [xun082/create-neat#4]
想问一下，作者命令行交互出使用的inquier库还有用到其他的库嘛？
我使用Inquirer.js的样式是这样的
![image](https://github.com/xun082/react-cli/assets/50485199/d7bba4c6-76d3-4178-a689-c72822b2a326)
和你的样式不太一样

**Comment by WakerCN** [comment]
你好还想请教一个问题，readme里面带emoji的目录树是怎么弄出来的
![image](https://github.com/xun082/react-cli/assets/50485199/1f32d129-3046-4160-af16-b35de3e65988)

然后有个建议，其实我提的这两个问题和代码本身无关，不太应该放在issue中，更适合放在github的discussion模块，作者可以尝试一下🫡
例如inquier库：https://github.com/SBoudrias/Inquirer.js/discussions

**Comment by xun082** [comment]
使用的是一个vscode插件哦 **Todo Tree**

**Comment by WakerCN** [comment]
> 使用的是一个vscode插件哦 **Todo Tree**

todo tree 是一个管理TODO的插件，你是用插件的api嘛然后把这个目录结构打印出来的嘛
![image](https://github.com/xun082/react-cli/assets/50485199/f4a254b9-c2cd-4699-aad5-f943d73a8818)

**Comment by xun082** [comment]
我的是这样的
![image](https://github.com/xun082/react-cli/assets/73689580/59326d4b-82a8-4b96-97f8-ab94bfdca25c)

**Comment by WakerCN** [comment]
> 我的是这样的 ![image](https://user-images.githubusercontent.com/73689580/259915649-59326d4b-82a8-4b96-97f8-ab94bfdca25c.png)

谢谢，我找到了，应该是这个插件
https://marketplace.visualstudio.com/items?itemName=Shinotatwu-DS.file-tree-generator

**Comment by w2xi** [comment]
> 你好还想请教一个问题，readme里面带emoji的目录树是怎么弄出来的 ![image](https://private-user-images.githubusercontent.com/50485199/259912157-1f32d129-3046-4160-af16-b35de3e65988.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1Nzg2NzYsIm5iZiI6MTcwODU3ODM3NiwicGF0aCI6Ii81MDQ4NTE5OS8yNTk5MTIxNTctMWYzMmQxMjktMzA0Ni00MTYwLWFmMTYtYjM1ZGUzZTY1OTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA1MDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZjBkM2JmNGZkYWU1MWNhYmQ5ZWM5MjJhOGQzOWM0ODAzMzJjNDRhMzgzYjNlY2U5NmQ2Y2ExN2UzMjIzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c11VmXVUfJ34eQ2XM-v1G2E2S23pP-78oRIXUG1S3_k)
> 
> 然后有个建议，其实我提的这两个问题和代码本身无关，不太应该放在issue中，更适合放在github的discussion模块，作者可以尝试一下🫡 例如inquier库：https://github.com/SBoudrias/Inquirer.js/discussions

刚好看到这个 issue，那就厚颜推荐一下最近写的小工具 [treei](https://github.com/w2xi/treei) 😄

**Comment by JE-lee** [comment]
> > 你好还想请教一个问题，readme里面带emoji的目录树是怎么弄出来的 ![image](https://private-user-images.githubusercontent.com/50485199/259912157-1f32d129-3046-4160-af16-b35de3e65988.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1Nzg2NzYsIm5iZiI6MTcwODU3ODM3NiwicGF0aCI6Ii81MDQ4NTE5OS8yNTk5MTIxNTctMWYzMmQxMjktMzA0Ni00MTYwLWFmMTYtYjM1ZGUzZTY1OTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA1MDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZjBkM2JmNGZkYWU1MWNhYmQ5ZWM5MjJhOGQzOWM0ODAzMzJjNDRhMzgzYjNlY2U5NmQ2Y2ExN2UzMjIzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c11VmXVUfJ34eQ2XM-v1G2E2S23pP-78oRIXUG1S3_k)
> > 然后有个建议，其实我提的这两个问题和代码本身无关，不太应该放在issue中，更适合放在github的discussion模块，作者可以尝试一下🫡 例如inquier库：https://github.com/SBoudrias/Inquirer.js/discussions
> 
> 刚好看到这个 issue，那就厚颜推荐一下最近写的小工具 [treei](https://github.com/w2xi/treei) 😄

那也来个我的 https://github.com/JE-lee/dirview/tree/master 😂
