### ISSUE TITLE
建议把vue和react分开选择

### ISSUE THREAD

**Issue by duckiamduck** [xun082/create-neat#74]
### Is your feature request related to a problem? Please describe it

当pick type的时候先
从react或vue两者之间选择再去选择模板
```
? Please choose a template (Use arrow keys)
> Vue
  React
```

### Describe the solution you'd like

一开始选择时

### What is the motivation / use case for changing the behavior?

好分类选择

**Comment by xun082** [comment]
目前正在开发阶段，请问你想参与吗，想参与的话可以加我微信了解更详细的需求 yunmz777
